Repository jupyterhub/pytest-jupyterhub, pull requests merged in 2023-01, with the labels that each got.

#12 add summary of JupyterHub MockHub class and App fixture
  README.md
  docs/source/fixtures.md
  docs/source/index.md
Labels: documentation

#18 Add pre-commit config, flake8 config, enable autoflake
  .flake8
  .pre-commit-config.yaml
  .readthedocs.yaml
  CONTRIBUTING.md
  MANIFEST.in
  README.md
  docs/Makefile
  docs/make.bat
  docs/source/changelog.md
  docs/source/conf.py
  docs/source/fixtures.md
  docs/source/index.md
  pyproject.toml
  pytest_jupyterhub/__init__.py
  pytest_jupyterhub/_version.py
Labels: maintenance

#15 Add the skeleton for an initial plugin for spawners and register it as a project entrypoint
  pyproject.toml
  pytest_jupyterhub/jupyterhub_spawners.py
Labels: enhancement
