Repository jupyterhub/pytest-jupyterhub, pull requests merged in 2023-04, with the labels that each got.

#50 dependabot: monthly updates of github actions
  .github/dependabot.yaml
  .github/dependabot.yml
Labels: maintenance

#48 Create release workflow file
  .github/workflows/release.yaml
Labels: enhancement

#39 Update readme with Usage instructions
  CONTRIBUTING.md
  README.md
Labels: documentation

#52 Changelog for 0.1.0
  docs/source/changelog.md
Labels: documentation

#59 Add RELEASE.md, and update release workflow to use PyPI's trusted publisher
  .github/workflows/release.yaml
  RELEASE.md
  docs/source/changelog.md
Labels: maintenance
